name: "Tagged Release Build"

on:
  push:
    tags:
      - 'v*'  # Triggers on tag push like v1.0.0

jobs:
  build:
    name: Build & Distribute
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
        env:
          LANG: en_US.UTF-8

      - name: Build iOS IPA (no signing)
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Distribute Android APK to Firebase
        run: |
          firebase appdistribution:distribute build/app/outputs/apk/release/app-armeabi-v7a-release.apk \
            --app 1:427445952125:android:7761a2707cbef894149b14 \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            --testers "email1@example.com,email2@example.com"


      - name: Distribute iOS IPA to Firebase
        run: |
          firebase appdistribution:distribute build/ios/iphoneos/app.ipa \
            --app 1:427445952125:android:7761a2707cbef894149b14 \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            --testers "email1@example.com,email2@example.com"


      - name: Upload to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk
            build/ios/iphoneos/app.ipa
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
